Example for functional connectivity
pyRiemann/pyRiemann pull request #202
Opened 2022-09-29 13:24 UTC by mccorsi

Hello,

With Sylvain Chevallier, we worked on an example that uses coherence function from pyriemann to build an ensemble classifier and compares the results with those from the state-of-the-art methods.

This approach is based on the one proposed in:
Corsi, M.-C., Chevallier, S., De Vico Fallani, F. & Yger, F. (2022). Functional connectivity ensemble method to enhance BCI performance (FUCONE). IEEE TBME. http://doi:10.1109/TBME.2022.3154885

This example reuses data from the EEGBCI dataset already used in the documentation.

Best,
Marie-Constance Corsi.

2022-09-29 20:01 UTC, agramfort reviewed
can you share the rendered doc page when you have it?

2022-09-29 20:01 UTC, agramfort commented on examples/motor-imagery/plot_ensemble_coherence.py
> +    FunctionalTransformer,
move the class definition here. It's part of the tutorial

2022-09-29 20:01 UTC, agramfort commented on examples/motor-imagery/plot_ensemble_coherence.py
> +            ("LogistReg", LogisticRegression(**param_lr))]
```suggestion
            ("LogReg", LogisticRegression(**param_lr))]
```

2022-09-29 20:01 UTC, agramfort commented on examples/motor-imagery/plot_ensemble_coherence.py
> +filterwarnings(action="ignore", category=ConvergenceWarning)
I don't like this very much

2022-09-29 20:01 UTC, agramfort commented on examples/motor-imagery/plot_ensemble_coherence.py
> +filterwarnings(action="ignore", category=ConvergenceWarning)
as this is not specific to a context

2022-09-30 18:04 UTC, qbarthelemy requested changes
Great contribution!

2022-12-09 06:48 UTC, qbarthelemy requested changes
Thx for this contribution, and to improve test base.

2022-12-10 18:50 UTC, sylvchev commented on examples/motor-imagery/helpers/coherence_helpers.py
> +class EnsureSPD(TransformerMixin, BaseEstimator):
Isn't the transformer misleading here? It select the nearest SPD matrix based on heuristic, IMO this is not a transformation or a projection, more like a hack. What about `NearestSPD` ?

2022-12-10 18:52 UTC, sylvchev commented on examples/motor-imagery/plot_ensemble_coherence.py
> +        return Xfc
That was our original move, but @agramfort suggested to move this into the example as this is part of the explanation.

2022-12-12 08:37 UTC, qbarthelemy commented on examples/motor-imagery/helpers/coherence_helpers.py
> +class EnsureSPD(TransformerMixin, BaseEstimator):
Ok for `NearestSPD`.

2022-12-12 08:39 UTC, qbarthelemy commented on examples/motor-imagery/plot_ensemble_coherence.py
> +        return Xfc
If ever another example needs this class, it will not be able to reuse it.

2022-12-12 13:54 UTC, qbarthelemy commented on examples/motor-imagery/plot_ensemble_coherence.py
> +        return Xfc
```suggestion

    def fit(self, X, y=None):
        self._coh = Coherences(
            coh=self.method,
            fmin=self.fmin,
            fmax=self.fmax,
            fs=self.fs,
        )
        return self

    def transform(self, X):
        X_coh = self._coh.fit_transform(X)
        X_con = X_coh.mean(axis=-1)
        return X_con
```

2022-12-19 17:22 UTC, qbarthelemy commented on doc/whatsnew.rst
> +- Add example on ensemble learning applied to functional connectivity, and add :func:`pyriemann.utils.base.nearest_pos_def`. :pr:`202` by :user:`mccorsi` and :user:`sylvchev`
```suggestion
- Add example on ensemble learning applied to functional connectivity, and add :func:`pyriemann.utils.base.nearest_sym_pos_def`. :pr:`202` by :user:`mccorsi` and :user:`sylvchev`
```

2022-12-19 17:22 UTC, qbarthelemy commented on examples/motor-imagery/helpers/coherence_helpers.py
> +# License: BSD (3-clause)
This could be removed.

2022-12-19 18:19 UTC, qbarthelemy approved these changes
Thx @mccorsi and @sylvchev !

2022-12-19 18:21 UTC, qbarthelemy commented
However, documentation build is KO.

2022-12-19 18:24 UTC, sylvchev commented
> However, documentation build is KO.

Yes, `examples/signal/plot_covariance_estimation.py` seems to have trouble to generate filled error bar.

2022-12-20 10:19 UTC, qbarthelemy commented
https://github.com/matplotlib/matplotlib/issues/24773

2022-12-20 15:28 UTC, qbarthelemy commented
Doc build is OK.
Solution found here https://github.com/mwaskom/seaborn/pull/3194

2022-12-21 14:45 UTC, sylvchev commented
Thanks @qbarthelemy , I checked the doc and all is ok. Ready to merge!

2022-12-21 18:32 UTC, merged