Speed up doc action
pyRiemann/pyRiemann pull request #316
Opened 2024-07-19 19:45 UTC by gcattan

- Just keep subjects 1 and 7

2024-07-22 10:18 UTC, qbarthelemy requested changes

2024-07-22 10:18 UTC, qbarthelemy commented on examples/motor-imagery/plot_augmented.py
> +runs = [6, 10]  # motor imagery: hands vs feet
Display is broken: without run 14, curves of results are flat.

I suggest to keep run 14, but to reduce grid search:

```
param_grid = {
    'augmenteddataset__order': [2, 3, 4],
    'augmenteddataset__lag': [5, 7, 9],
}
```

2024-07-22 14:56 UTC, AmmarMian commented
Sounds good to me to reduce time !

2024-07-23 10:56 UTC, qbarthelemy requested changes

2024-07-23 16:29 UTC, merged

2024-07-23 16:29 UTC, qbarthelemy commented
Thx a lot @gcattan !

2024-07-23 18:31 UTC, gcattan commented
Thx @qbarthelemy !