Log cholesky
pyRiemann/pyRiemann pull request #322
Opened 2024-09-10 08:18 UTC by gabelstein

Implementation of full framework of log-cholesky metric from [Lin (2019)](https://arxiv.org/pdf/1908.09326).
Kernel is unpublished, so maybe we want to cut it out until it is published? Or just keep it in there with a note to the paper in progress.
I also extended it to work with HPD matrices which the original paper does not include. Not sure if that needs a disclaimer.

The logchol distance that was previously implemented does not directly relate to this paper but was introduced in a [different context](https://doi.org/10.1214/09-AOAS249) and should much rather be termed the cholesky distance.
Not sure if that need a deprecation first.
It would be quite simple to extend the simple cholesky distance to a full RIemannian metric constructing it as a pullback metric using chol as the pullback from the space of lower triangular matrices with positive diagonals with the euclidean metric. But it would roughly be about as useful as the Euclidean metric for SPD matrices, so probably not worth the struggle.

I hope I extended all the test and docs well, but someone should thoroughly check please.

2024-09-10 11:13 UTC, qbarthelemy requested changes
Thanks for spotting this confusion in the Cholesky distance implementation!
Don't forget to complete the whatsnew file.

Regarding the log-Cholesky kernel, I am not in favor of adding unpublished methods into pyRiemann.

2024-09-11 11:15 UTC, gabelstein commented
@qbarthelemy Alright, I will remove the kernel. 
I personally would prefer to always write out the name "cholesky" as opposed to using "chol".
Some users might not intuitively know what logchol means.
But my heart does not cling to the function names, so if you insist we can call it logchol.

2024-09-11 11:18 UTC, gabelstein commented on pyriemann/utils/mean.py
> +    mean[..., tr0, tr1] = np.average(X_chol[..., tr0, tr1], axis=0,
Yes, you are right.

2024-09-11 11:54 UTC, qbarthelemy commented
To avoid long function names, `*_logeuclidean` was shortened to `*_logeuclid`. 
Similarly, `*_logcholesky` is too long, that's why I proposed to shorten it to `*_logchol`.
I don't see what intermediate version to find.

2024-09-13 11:02 UTC, qbarthelemy commented on doc/api.rst
> +    kernel_logcholesky
```suggestion
```

2024-09-13 11:03 UTC, qbarthelemy commented on pyriemann/utils/mean.py
> +    return mean @ mean.conj().swapaxes(-2, -1)
```suggestion
    mean[tr0, tr1] = np.average(
        X_chol[:, tr0, tr1],
        axis=0,
        weights=sample_weight,
    )
    mean[diag0, diag1] = np.exp(np.average(
        np.log(X_chol[:, diag0, diag1]),
        axis=0,
        weights=sample_weight,
    ))
    return mean @ mean.conj().T
```

2024-09-20 10:58 UTC, qbarthelemy commented
@gabelstein , can you check if the latest version of the code suits you?

2024-09-20 12:08 UTC, gabelstein commented
@qbarthelemy very good, thank you!

2024-09-20 15:17 UTC, qbarthelemy commented
Are there any specific properties we could check for Cholesky or log-Cholesky metrics?

2024-09-20 15:18 UTC, qbarthelemy approved these changes

2024-09-27 17:55 UTC, qbarthelemy commented
Are there any specific properties we could check for Cholesky or log-Cholesky metrics?
Or, can I merge? @gabelstein

2024-09-27 18:33 UTC, gabelstein commented
On vacation right now. Can check next week.Am 27.09.2024 19:55 schrieb Quentin Barthélemy ***@***.***>:
Are there any specific properties we could check for Cholesky or log-Cholesky metrics?
Or, can I merge? @gabelstein

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-03 11:39 UTC, qbarthelemy commented
I merge. We will make another pull request to complete the tests if necessary.

2024-10-03 11:40 UTC, merged